spring:
 datasource:
  url: jdbc:mariadb://localhost:3306/alura-loja?createDatabaseIfNotExist=true
  username: root
  password: root
  driver-class-name: org.mariadb.jdbc.Driver
  initialization-mode: always
 jpa:
   open-in-view: false
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   generate-ddl: true
#   hibernate:
#     naming:
#       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#       implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
   properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show_sql: true
      format_sql: true
      ddl-auto: create
logging:
  level:
    org:
      hibernate:
        type: info
        
